backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/about.html"
        label: "About"
        name: "about"
        fields:
          - { label: "HTML", name: "body", widget: "code", default: '', mode: 'html' }
      - file: "content/szpp.html"
        label: "SZPP"
        name: "szpp"
        fields:
          - { label: "HTML", name: "body", widget: "code", default: '', mode: 'html' }
      - file: "content/contact.html"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "HTML", name: "body", widget: "code", default: '', mode: 'html' }
